name: Mark

on 
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pobierz kod
      uses: actions/checkout@v4
    - name: Node.js
      run: node test.js
    